Table Flowers {
    id int [pk]
    commonName varchar
    colorId int [ref: - Colors.id]
}

Table Colors {
    id int [pk]
    name varchar
}

Table Nurseries {
    id int [pk]
    name varchar
}

Table FlowerRetailers {
    id int [pk]
    name varchar
    cityId int [ref: - Cities.id]
    stateId int [ref: - States.id]
    address varchar
    distributorId int [ref: - FlowerDistributors.id]
}

Table FlowerDistributors {
    id int [pk]
    name varchar
    cityId int [ref: - Cities.id]
    stateId int [ref: - States.id]
    address varchar
}

Table flowerExchanges {
    id int [pk]
    flowerId int [ref: > Flowers.id]
    nurseryId int [ref: > Nurseries.id]
    flowerDistributorId int [ref: > FlowerDistributors.id]
}

Table States {
    id int [pk]
    name varchar
}

Table Cities {
    id int [pk]
    name varchar
}