Table Flowers {
    id int [pk]
    commonName varchar
    color varchar
}

Table Nurseries {
    id int [pk]
    name varchar
    flowerId int [ref: > Flowers.id]
}

Table FlowerRetailers {
    id int [pk]
    name varchar
    city varchar
    state varchar
    address varchar
}

Table FlowerDistributors {
    id int [pk]
}